SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE `ajxp_repo_options` (
  `oid` int(11) NOT NULL AUTO_INCREMENT,
  `uuid` varchar(33) NOT NULL,
  `name` varchar(50) NOT NULL,
  `val` varchar(2000) DEFAULT NULL,
  PRIMARY KEY (`oid`),
  KEY `ajxp_repo_options_uuid_idx` (`uuid`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
